version: '3'
services:
  nextjs:
    image: richardkovacs/nextjs:13
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000
    command: npm run dev
